travis:
  secure:
    BINSTAR_TOKEN: oVHTFwC7F5qUYWFwZmJNOTcCc9ayLdCK5mN1qyMyCeJdro7yAD9vwROP56JuvRH7ouYM5HvADl3yzS5HKOWWox/Z1nHInO9wqD9rClRejijAxVysw/FoE3fiB5myJRVVMBv7Fjz//JV2bkm/zC5BrZMOuYpb9+c4yqzH2uaCSiZBSUOo25EpK9T20Jo6RV5UvLkJCvsHnO1sxK7tGNZQxzv/YpYMJmf19ClcsVL/ZD3lgLwpILb/KVA1N042pJi9G/1nv2KoTyZFPVsSuR7jtdJBJfJXe45q2ZTKxanHsCo/gi0rxEnz7h1NWuarbjkWaZoJfl5Q4vHgUmpNZW8kH5JiCUYxtrtNJrTftYeDCJ6ur9uX2Cbspih2zmqyCW3vc/JS13wxFZ5GK8XYF9VwiQ2Yt0Rsuzb9gp564KRGvn1o1SB9LjopR5lzrgahWmXyxlMjxy6ous+G0/0UlfH4U8pn36tnwJZTnf0cbC4ra72D6i3L7zKGFd27Y7GAF+IPtwERvahxobLBkcthRtgVSNrCWekADhLVe7XaMq/DedpqaE7kFf4n45yInq7rfo+pJBP5/YWjyGa7KK67bpy4pGW4wSBu45T+wc07Tf12FHhQ62J/T1+pIP4aCSFiMoJ5HXTOSdJFsIuQGhKjmR1uF7RrY3G/3OjGzakOYz1Ff4s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
